server:
  port: 8262

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url.defaultZone: http://peer1:8260/eureka/,http://peer2:8261/eureka/
  instance:
    hostname: peer3
spring:
  application:
    name: servicediscovery
    profiles: dev
  boot:
    admin:
      client:
        url: http://localhost:8071
  zipkin:
    base-url: http://localhost:9411