logging:
  level:
    org:
      springframework: INFO
management:
  endpoints:
    exposure:
      include: refresh,info,health
    health:
      show-details: always
spring:
  devtools:
    restart:
      enabled: true
      exclude: test
