eureka:
  instance:
    prefer-id-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:8260/eureka,http://peer2:8261/eureka,http://peer3:8262/eureka
feign:
  hystrix:
    enabled: true

spring:
  devtools:
    restart:
      enabled: true
      exclude: test

management:
  endpoints:
    exposure:
      include: refresh,info,health
    health:
      show-details: always