server:
  port: 3030
eureka:
  instance:
    prefer-id-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:8260/eureka,http://peer2:8261/eureka,http://peer3:8262/eureka
spring:
  devtools:
    restart:
      enabled: true
      exclude: test
  cloud:
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username:
    password: 

management:
  endpoints:
    exposure:
      include: refresh,info,health
    health:
      show-details: always