server:
  port: 3030
eureka:
  instance:
    prefer-id-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:8260/eureka,http://peer2:8261/eureka,http://peer3:8262/eureka
spring:
  devtools:
    restart:
      enabled: true
      exclude: test

management:
  endpoints:
    exposure:
      include: refresh,info,health
    health:
      show-details: always